// Centralized parts library loader.
//
// As of 2026-06-21, the data source moved from `src/content/parts-library/*.json`
// to `src/content/parts-inventory/*.json` after merging the two collections
// into a single TinaCMS collection (see AI_PLAYBOOK Case Study 12).
//
// Each file in parts-inventory/ represents ONE unique part-concept and
// contains BOTH the structural fields (regenerated by scripts/scan-parts.mjs)
// AND the human-edited fields (image, notes).
//
// Schema: {
//   key, type, label, brand, machines[], occurrences, hasImage, sampleNames[],
//   image?, notes?         ← these two are human-edited via TinaCMS
// }
//
// Two lookup strategies:
//   1. lookupPart(brand, partId, partName, category?) — used by PartsTable
//      and the homepage. Three-tier strategy: brand:partId → brand:slugified
//      partName → concept-aware fallback (generic concepts share across
//      brands; brand-scoped concepts are looked up by brand+key).
//   2. lookupConcept(conceptKey, brand?) — used by /parts-inventory/ and
//      /parts-library/ pages when the concept key is already known.

import fs from "node:fs";
import path from "node:path";
import { CONCEPTS, type ConceptDef, conceptLookupKey, matchesConcept } from "./concepts";
import { withBase } from "./base";

export const PARTS_INVENTORY_DIR = path.join(process.cwd(), "src/content/parts-inventory");

export interface PartLibraryEntry {
  // Structural fields (regenerated by scan-parts, readonly in TinaCMS)
  key: string;
  type: "generic" | "brand-scoped";
  label: string;
  brand: string | null;
  machines: string[];
  occurrences: number;
  hasImage: boolean;
  sampleNames: string[];

  // Human-edited fields (editable in TinaCMS)
  image: string;
  notes: string;
}

let cache: PartLibraryEntry[] | null = null;
let lookupCache: Map<string, PartLibraryEntry> | null = null;

function listJsonFiles(): string[] {
  if (!fs.existsSync(PARTS_INVENTORY_DIR)) return [];
  return fs.readdirSync(PARTS_INVENTORY_DIR).filter((f) => f.endsWith(".json"));
}

function loadAll(): PartLibraryEntry[] {
  if (cache) return cache;
  cache = listJsonFiles().map((file) => {
    try {
      const raw = fs.readFileSync(path.join(PARTS_INVENTORY_DIR, file), "utf-8");
      const data = JSON.parse(raw) as Partial<PartLibraryEntry>;
      return {
        key: (data.key || file.replace(/\.json$/, "")).toString(),
        type: (data.type || "generic") as "generic" | "brand-scoped",
        label: (data.label || "").toString(),
        brand: data.brand ?? null,
        machines: Array.isArray(data.machines) ? data.machines : [],
        occurrences: typeof data.occurrences === "number" ? data.occurrences : 0,
        hasImage: !!data.hasImage,
        sampleNames: Array.isArray(data.sampleNames) ? data.sampleNames : [],
        image: (data.image || "").toString(),
        notes: (data.notes || "").toString(),
      } as PartLibraryEntry;
    } catch (err) {
      // Skip malformed files but log the failure
      // eslint-disable-next-line no-console
      console.warn(`[parts-library] Skipped malformed file: ${file}`, err);
      return null;
    }
  }).filter((e): e is PartLibraryEntry => e !== null);
  return cache;
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function buildLookup(): Map<string, PartLibraryEntry> {
  if (lookupCache) return lookupCache;
  const map = new Map<string, PartLibraryEntry>();
  for (const entry of loadAll()) {
    // Index by canonical concept key. Generic concepts (type === "generic")
    // are looked up by key alone; brand-scoped are indexed by brand+key.
    if (entry.type === "generic") {
      if (!map.has(entry.key)) map.set(entry.key, entry);
    } else if (entry.brand) {
      const brandLower = entry.brand.toLowerCase().trim();
      const k = `${brandLower}:${entry.key}`;
      if (!map.has(k)) map.set(k, entry);
      // Also index by just the key, as a fallback (so lookups that already
      // know the full key like "juki-bobbin" work without the brand prefix).
      if (!map.has(entry.key)) map.set(entry.key, entry);
    }
    // Index by brand:partId where partId is in sampleNames (legacy support).
    // The new schema doesn't have a separate partId field, so this is a no-op
    // for now — sample names are free-form partName strings from the catalog.
  }
  lookupCache = map;
  return lookupCache;
}

/**
 * Look up a part in the inventory by brand + sample name.
 *
 * For a parts table row that says { brand: "JUKI", partName: "Bobbin and Bobbin
 * Case", partId: "..." }, the lookup walks the inventory and returns the
 * matching entry — or undefined if no concept match was found.
 *
 * @returns The matching inventory entry, or undefined if no match found.
 *          Caller should show a "No image uploaded yet" placeholder.
 */
export function lookupPart(
  brand: string | undefined,
  partId: string | undefined,
  partName: string | undefined,
  category?: string
): PartLibraryEntry | undefined {
  if (!brand) return undefined;
  const lookup = buildLookup();
  const b = brand.toLowerCase().trim();

  // Strategy 1: brand:conceptKey — try every brand-scoped entry whose key
  // appears in the part's name or partId. This handles the common case
  // where the part name explicitly contains the concept (e.g. "Bobbin
  // and Bobbin Case" matches the `juki-bobbin` key via the JUKI brand prefix).
  for (const entry of loadAll()) {
    if (entry.type !== "brand-scoped") continue;
    if (!entry.brand) continue;
    if (entry.brand.toLowerCase().trim() !== b) continue;
    // The key has the brand prefix stripped (e.g. "juki-bobbin" → "bobbin").
    // Check if the part's name or id mentions the concept label or any sample name.
    const conceptKey = entry.key.replace(new RegExp(`^${slugify(entry.brand)}-`), "");
    if (
      (partName && partName.toLowerCase().includes(conceptKey.replace(/-/g, " "))) ||
      (partName && partName.toLowerCase().includes(conceptKey)) ||
      (partId && partId.toLowerCase().includes(conceptKey)) ||
      entry.sampleNames.some((sn) => partName && partName.toLowerCase() === sn.toLowerCase())
    ) {
      return entry;
    }
  }

  // Strategy 2: concept-aware fallback using matchesConcept(). This is
  // how a generic concept (e.g. needle-generic) appears for every brand.
  const concept = matchesConcept(partName || "", partId || "", category || "", brand);
  if (concept) {
    return lookupConcept(concept.key, brand);
  }

  return undefined;
}

/**
 * Look up a part via its concept key.
 *
 * - Generic concepts (needle-dc27, needle-generic): lookup by concept key alone.
 * - Brand-scoped concepts (juki-bobbin): lookup by brand+concept key.
 *
 * @returns The matching inventory entry, or undefined.
 */
export function lookupConcept(
  conceptKey: string,
  brand?: string
): PartLibraryEntry | undefined {
  const lookup = buildLookup();
  if (!brand) return lookup.get(conceptKey);
  const brandLower = brand.toLowerCase().trim();
  // Try brand-prefixed key first, then plain key as fallback.
  return lookup.get(`${brandLower}:${conceptKey}`) || lookup.get(conceptKey);
}

/**
 * Build the lookup key for a concept + brand combination. Exposed for the
 * inventory scanner and click-through URL generation.
 */
export function keyForConcept(concept: ConceptDef, brand: string): string {
  return conceptLookupKey(concept, brand);
}

/**
 * Return all library entries (for admin listings, search, etc).
 */
export function getAllParts(): PartLibraryEntry[] {
  return loadAll();
}

/**
 * Build the pre-filled TinaCMS deep-link URL for creating a new
 * `partsInventory` entry. Centralised here so the PartsTable inline
 * badges and /parts-inventory/ page stay in sync.
 *
 * Pattern:
 *   <prefix>/admin/#/~/partsInventory/new?key=<key>&brand=<brand>&partName=<partName>
 *
 * The prefix depends on environment:
 *   - DEV  (`astro dev` only): `http://localhost:4001` — TinaCMS's own
 *     Vite dev server, which is NOT proxied through Astro. Astro dev
 *     does not serve `/admin/`, so a same-origin link from Astro dev
 *     returns 404. Pointing to TinaCMS dev directly is the only way
 *     the badge works while running locally.
 *   - PROD: `<siteBase>/admin/` (e.g. `/Machines/admin/`) — the bundled
 *     SPA shipped to GitHub Pages.
 *
 * If both servers run together via `npm run cms`
 * (`tinacms dev -c "astro dev"`), TinaCMS proxies port 4001 → 4321 and
 * the same-origin Astro URL would also work. We default to the dev
 * server anyway because most developers run `npm run dev` first.
 *
 * `brand` is optional — for generic concepts (Needle DC×27, Bearing 608ZZ)
 * the entry has no brand prefix and we omit the query param so TinaCMS
 * leaves the field blank.
 */
export function buildPartsLibraryNewUrl(opts: {
  key: string;
  brand?: string;
  partName: string;
}): string {
  const params = new URLSearchParams();
  params.set("key", opts.key);
  if (opts.brand && opts.brand.trim().length > 0) {
    params.set("brand", opts.brand);
  }
  params.set("partName", opts.partName);
  const hash = `#/~/partsInventory/new?${params.toString()}`;
  if (import.meta.env.DEV) {
    return `http://localhost:4001/admin/${hash}`;
  }
  return withBase(`/admin/${hash}`);
}